name: Deploy Streamlit App to Azure VM

on:
  push:
    branches:
      - main  # Replace 'main' with the branch you want to use for deployment

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the code from the GitHub repository
      - name: Check out the code
        uses: actions/checkout@v3

      # Step 2: Set up SSH access to the Azure VM
      - name: Set up SSH
        env:
          AZURE_VM_SSH_KEY: ${{ secrets.AZURE_VM_SSH_KEY }}
          AZURE_VM_IP: ${{ secrets.AZURE_VM_IP }}
        run: |
          echo "Azure VM IP: $AZURE_VM_IP"  # Debugging step to verify IP address
          
          # Create the .ssh directory with appropriate permissions
          mkdir -p ~/.ssh
          chmod 700 ~/.ssh
          
          # Save the SSH private key and set permissions
          echo "$AZURE_VM_SSH_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          
          # Add the VM's IP to known_hosts to prevent SSH prompt
          ssh-keyscan -H "$AZURE_VM_IP" >> ~/.ssh/known_hosts || true

      # Step 3: Deploy the application files to the Azure VM
      - name: Deploy to Azure VM
        env:
          AZURE_VM_IP: ${{ secrets.AZURE_VM_IP }}
          AZURE_VM_USERNAME: ${{ secrets.AZURE_VM_USERNAME }}
        run: |
          echo "Deploying to $AZURE_VM_USERNAME@$AZURE_VM_IP"  # Debugging step to verify username and IP
          
          # Copy application files to the target directory on the VM
          scp -o StrictHostKeyChecking=no -r * $AZURE_VM_USERNAME@$AZURE_VM_IP:/home/$AZURE_VM_USERNAME/streamlit_app/

      # Step 4: Run Streamlit App on Azure VM
      - name: Run Streamlit App
        env:
          AZURE_VM_IP: ${{ secrets.AZURE_VM_IP }}
          AZURE_VM_USERNAME: ${{ secrets.AZURE_VM_USERNAME }}
        run: |
          ssh $AZURE_VM_USERNAME@$AZURE_VM_IP << EOF
            cd /home/$AZURE_VM_USERNAME/streamlit_app
            pkill -f streamlit || true
            nohup streamlit run app.py --server.port=8501 &
          EOF
